### ISSUE TITLE
Cannot create GitHub issue - missing Octokit assembly

### ISSUE THREAD

**Issue by brettveenstra** [aliozgur/SeqApps#10]
Configured v0.1.0 connected to GitHub, receving the following message when attempting to “Send to App”

GitHub Issues v0.1.0
Seq v4.2.1113

```
System.IO.FileNotFoundException: Could not load file or assembly 'Octokit, Version=0.23.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.
File name: 'Octokit, Version=0.23.0.0, Culture=neutral, PublicKeyToken=null'
   at SeqApps.GitHub.GitHubIssueReactor.CreateIssue(Event`1 evt)
   at SeqApps.GitHub.GitHubIssueReactor.On(Event`1 evt)


```

**Comment by aliozgur** [comment]
Duplicates #11
